### ISSUE TITLE
Numix Flatstudio Dark - Firefox about:config Can't Read...

### ISSUE THREAD

**Issue by ghost** [dirruk1/Numix-Flatstudio#1]
Hi,

I'm using Numix Flatstudio Dark and noticed with Firefox 38.2.0 ESR, that in about:config it's dark and hard to read the text.

Not sure if this happens in other versions of Firefox, but I use ESR.

Please see the screen shot below;

http://i.imgur.com/b63GVCm.jpg

**Comment by ghost** [comment]
COCK A DOODLE DOO!

Seriously, is anyone breathing around here?

I would GREATLY appreciate a reply to getting this fixed?

thank you... :)

**Comment by ghost** [comment]
Hmm I guess no hope on this... :(

**Comment by samhed** [comment]
:(

**Comment by ghost** [comment]
I'm now using 45.3.0 ESR and about:config looks good.

I guess just something going on with the older version of Firefox, so all good for now! :)
